CREATE TABLE `customers`(
    `id` BIGINT(20) UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    `name` VARCHAR(255) NOT NULL,
    `email` VARCHAR(255) NOT NULL,
    `location` VARCHAR(255) NOT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIME(),
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIME ON UPDATE CURRENT_TIMESTAMP()
)